services:

  mysql:
    image: mysql:8.4
    container_name: product-mysql
    restart: always
    working_dir: /app

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  product-service:
    build: .
    container_name: product-service
    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  default:
    external: true
    name: ecommerce-network